import { useState } from "react";
import { trpc } from "@/lib/trpc";

const stageLabels = { accountant: "المحاسب", reviewer: "المراجع", cfo: "المدير المالي", gm: "المدير العام", auditor: "المدقق" } as const;
type Stage = keyof typeof stageLabels;
const defaultStages: Stage[] = ["accountant", "reviewer", "cfo", "gm", "auditor"];

export function ApprovalPoliciesPanel() {
  const [message, setMessage] = useState("");
  const [policyName, setPolicyName] = useState("المسار الخماسي الافتراضي");
  const [stages, setStages] = useState<Stage[]>(defaultStages);
  const [allowSkip, setAllowSkip] = useState(false);
  const [delegateRole, setDelegateRole] = useState<Stage>("gm");
  const [delegateUserId, setDelegateUserId] = useState("");
  const [startsAt, setStartsAt] = useState("");
  const [endsAt, setEndsAt] = useState("");
  const [reason, setReason] = useState("");
  const policies = trpc.approval.policies.useQuery(undefined);
  const delegations = trpc.approval.delegations.useQuery(undefined);
  const users = trpc.users.list.useQuery(undefined);
  const createPolicy = trpc.approval.createPolicy.useMutation({ onSuccess: () => { setMessage("تم حفظ سياسة المسار. ستُطبّق على الطلبات الجديدة فقط."); void policies.refetch(); }, onError: (error) => setMessage(error.message) });
  const createDelegation = trpc.approval.createDelegation.useMutation({ onSuccess: () => { setMessage("تم إنشاء التفويض المؤقت وتسجيله في التدقيق."); setReason(""); setDelegateUserId(""); void delegations.refetch(); }, onError: (error) => setMessage(error.message) });
  const deactivateDelegation = trpc.approval.deactivateDelegation.useMutation({ onSuccess: () => { setMessage("تم إيقاف التفويض."); void delegations.refetch(); }, onError: (error) => setMessage(error.message) });
  const toggleStage = (stage: Stage) => setStages((current) => current.includes(stage) ? current.filter((item) => item !== stage) : [...current, stage]);
  const submitPolicy = () => { if (!stages.length) { setMessage("اختر مرحلة واحدة على الأقل."); return; } createPolicy.mutate({ name: policyName.trim(), stages, allowSkip }); };
  const submitDelegation = () => { const delegateId = Number(delegateUserId); if (!delegateId || !startsAt || !endsAt || !reason.trim()) { setMessage("أكمل المستخدم المفوّض والتاريخ والسبب."); return; } createDelegation.mutate({ fromRole: delegateRole, delegateUserId: delegateId, startsAt: new Date(startsAt), endsAt: new Date(endsAt), reason: reason.trim() }); };
  return <div className="mt-5 grid gap-5 lg:grid-cols-2" dir="rtl">
    <div className="rounded-2xl border bg-card p-5"><h3 className="font-display text-lg font-extrabold">سياسات مسارات الاعتماد</h3><p className="mt-1 text-xs leading-6 text-muted-foreground">أنشئ مساراً للطلبات الجديدة فقط. الطلبات القائمة تحتفظ بنسخة مسارها.</p><input value={policyName} onChange={(event) => setPolicyName(event.target.value)} className="mt-4 w-full rounded-xl border bg-background px-3 py-3 text-sm" placeholder="اسم السياسة" aria-label="اسم سياسة الاعتماد"/><div className="mt-4 grid gap-2 sm:grid-cols-2">{(Object.keys(stageLabels) as Stage[]).map((stage) => <label key={stage} className="flex items-center gap-2 rounded-xl bg-secondary px-3 py-3 text-sm"><input type="checkbox" checked={stages.includes(stage)} onChange={() => toggleStage(stage)}/><span>{stageLabels[stage]}</span></label>)}</div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={allowSkip} onChange={(event) => setAllowSkip(event.target.checked)}/> السماح بالتجاوز المصرح مع سبب إلزامي</label><button disabled={createPolicy.isPending} onClick={submitPolicy} className="mt-4 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground disabled:opacity-50">{createPolicy.isPending ? "جارٍ الحفظ…" : "حفظ سياسة جديدة"}</button><div className="mt-5 space-y-2">{policies.isLoading ? <p className="text-xs text-muted-foreground">جارٍ التحميل…</p> : (policies.data ?? []).map((policy) => <div key={policy.id} className="rounded-xl bg-secondary px-3 py-3 text-sm"><div className="flex items-center justify-between gap-3"><span className="font-bold">{policy.name}</span><span className="text-xs text-primary">{policy.isActive ? "نشطة" : "متوقفة"}</span></div><p className="mt-1 text-xs text-muted-foreground">المراحل: {Array.isArray(policy.stages) ? policy.stages.map((stage) => stageLabels[String(stage) as Stage] ?? String(stage)).join(" ← ") : "المسار الافتراضي"}</p></div>)}</div></div>
    <div className="rounded-2xl border bg-card p-5"><h3 className="font-display text-lg font-extrabold">تفويض مؤقت</h3><p className="mt-1 text-xs leading-6 text-muted-foreground">استخدم التفويض عند السفر أو الغياب. لا تشارك الحساب أو الرمز السري.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={delegateRole} onChange={(event) => setDelegateRole(event.target.value as Stage)} className="rounded-xl border bg-background px-3 py-3 text-sm" aria-label="المرحلة المفوضة">{(Object.keys(stageLabels) as Stage[]).map((stage) => <option key={stage} value={stage}>{stageLabels[stage]}</option>)}</select><select value={delegateUserId} onChange={(event) => setDelegateUserId(event.target.value)} className="rounded-xl border bg-background px-3 py-3 text-sm" aria-label="المستخدم المفوّض"><option value="">اختر المستخدم المفوّض</option>{(users.data ?? []).map((user) => <option key={user.id} value={user.id}>{user.name}{user.operationalRole ? ` — ${user.operationalRole}` : ""}</option>)}</select><input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} className="rounded-xl border bg-background px-3 py-3 text-sm" aria-label="بداية التفويض"/><input type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} className="rounded-xl border bg-background px-3 py-3 text-sm" aria-label="نهاية التفويض"/><textarea value={reason} onChange={(event) => setReason(event.target.value)} className="min-h-24 rounded-xl border bg-background px-3 py-3 text-sm sm:col-span-2" placeholder="سبب التفويض الإلزامي" aria-label="سبب التفويض"/></div><button disabled={createDelegation.isPending} onClick={submitDelegation} className="mt-4 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground disabled:opacity-50">{createDelegation.isPending ? "جارٍ الحفظ…" : "إنشاء التفويض"}</button><div className="mt-5 space-y-2">{(delegations.data ?? []).map((delegation) => <div key={delegation.id} className="flex items-center justify-between gap-3 rounded-xl bg-secondary px-3 py-3 text-xs"><span>{stageLabels[delegation.fromRole as Stage] ?? delegation.fromRole} · {new Date(delegation.startsAt).toLocaleDateString("ar-SA")} إلى {new Date(delegation.endsAt).toLocaleDateString("ar-SA")}</span>{delegation.isActive && <button onClick={() => deactivateDelegation.mutate({ id: delegation.id })} className="font-bold text-destructive">إيقاف</button>}</div>)}</div></div>{message ? <p className="lg:col-span-2 text-sm font-semibold text-primary">{message}</p> : null}
  </div>;
}
