import { useMemo, useState } from "react";
import { Download, FileSpreadsheet, FileText, RefreshCw } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { downloadCsv, downloadExcel, downloadPdf } from "@/lib/reportExports";

export function FinancialReportsPanel() {
  const [companyId, setCompanyId] = useState<number | undefined>();
  const [fiscalYearId, setFiscalYearId] = useState<number | undefined>();
  const [isExporting, setIsExporting] = useState(false);
  const [exportMessage, setExportMessage] = useState("");
  const filters = useMemo(() => ({ ...(companyId ? { companyId } : {}), ...(fiscalYearId ? { fiscalYearId } : {}) }), [companyId, fiscalYearId]);
  const companies = trpc.entities.companies.list.useQuery();
  const fiscalYears = trpc.settings.fiscalYears.useQuery();
  const report = trpc.reports.financial.useQuery(filters);
  const logExport = trpc.reports.logExport.useMutation();
  const rows = report.data ?? [];
  const totalAmount = rows.reduce((sum, row) => sum + Number(row.amount ?? 0), 0);
  const statusCounts = rows.reduce<Record<string, number>>((counts, row) => { counts[row.status] = (counts[row.status] ?? 0) + 1; return counts; }, {});
  const currencyCounts = rows.reduce<Record<string, number>>((counts, row) => { counts[row.currency] = (counts[row.currency] ?? 0) + 1; return counts; }, {});
  const summaryLabel = Object.entries(currencyCounts).map(([currency, count]) => `${currency}: ${count}`).join(" · ");
  const scope = [companyId ? "company" : "all-companies", fiscalYearId ? "year" : "all-years"].join("-");
  const exportReport = async () => { if (isExporting) return; setIsExporting(true); setExportMessage(""); try { await logExport.mutateAsync({ format: "csv", ...filters, recordCount: rows.length }); downloadCsv(rows, `trezo-financial-report-${scope}.csv`); } catch (error) { setExportMessage(`تعذر تصدير CSV: ${error instanceof Error ? error.message : "أعد المحاولة"}`); } finally { setIsExporting(false); } };
  const exportExcel = async () => { if (isExporting) return; setIsExporting(true); setExportMessage(""); try { await logExport.mutateAsync({ format: "xlsx", ...filters, recordCount: rows.length }); downloadExcel(rows, `trezo-financial-report-${scope}.xls`); } catch (error) { setExportMessage(`تعذر تصدير Excel: ${error instanceof Error ? error.message : "أعد المحاولة"}`); } finally { setIsExporting(false); } };
  const exportPdf = async () => {
    if (isExporting) return;
    setIsExporting(true); setExportMessage("");
    try {
    await logExport.mutateAsync({ format: "pdf", ...filters, recordCount: rows.length });
    downloadPdf(rows, `trezo-financial-report-${scope}.pdf`, `${companyId ? `Company #${companyId}` : "All companies"} | ${fiscalYearId ? `Fiscal year #${fiscalYearId}` : "All fiscal years"}`);
    } catch (error) { setExportMessage(`تعذر تصدير PDF: ${error instanceof Error ? error.message : "أعد المحاولة"}`); } finally { setIsExporting(false); }
  };

  return <section className="mb-5 rounded-2xl border bg-card p-5 shadow-sm sm:p-6" aria-labelledby="financial-export-title">
    <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2 text-primary"><FileSpreadsheet size={20}/><h3 id="financial-export-title" className="font-display text-lg font-extrabold">تصدير التقرير المالي</h3></div><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">صدّر سجل طلبات الصرف بصيغة CSV أو Excel أو PDF رسمي بعد التصفية حسب الشركة والسنة المالية. لا يشمل التصدير أي أسعار صرف تقديرية، ويُظهر PDF نطاق التقرير وتاريخ إنشائه.</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={!rows.length || report.isLoading || logExport.isPending || isExporting} onClick={() => void exportReport()} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground transition-transform hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50"><Download size={17}/>{report.isLoading ? "جارٍ تجهيز التقرير…" : "تنزيل CSV"}</button><button type="button" disabled={!rows.length || report.isLoading || logExport.isPending || isExporting} onClick={() => void exportExcel()} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl border border-primary/30 px-4 py-3 text-sm font-bold text-primary transition-transform hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50"><FileSpreadsheet size={17}/>تنزيل Excel</button><button type="button" disabled={!rows.length || report.isLoading || logExport.isPending || isExporting} onClick={() => void exportPdf()} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl border border-primary/30 px-4 py-3 text-sm font-bold text-primary transition-transform hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50"><FileText size={17}/>تنزيل PDF رسمي</button></div></div>{exportMessage ? <p role="alert" className="mt-3 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm font-semibold text-destructive">{exportMessage} <button type="button" onClick={() => setExportMessage("")} className="mr-2 underline">إغلاق</button></p> : null}
    <div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-muted-foreground">الشركة<select value={companyId ?? ""} onChange={(event) => setCompanyId(event.target.value ? Number(event.target.value) : undefined)} className="mt-2 w-full rounded-xl border bg-background px-3 py-3 text-sm text-foreground"><option value="">كل الشركات</option>{(companies.data ?? []).map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label className="text-xs font-bold text-muted-foreground">السنة المالية<select value={fiscalYearId ?? ""} onChange={(event) => setFiscalYearId(event.target.value ? Number(event.target.value) : undefined)} className="mt-2 w-full rounded-xl border bg-background px-3 py-3 text-sm text-foreground"><option value="">كل السنوات</option>{(fiscalYears.data ?? []).map((year) => <option key={year.id} value={year.id}>{year.label}</option>)}</select></label></div>
    {report.error ? <div className="mt-4 flex flex-col gap-3 rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive sm:flex-row sm:items-center sm:justify-between"><span>تعذر تجهيز التقرير: {report.error.message}</span><button type="button" onClick={() => void report.refetch()} className="inline-flex items-center gap-2 self-start rounded-lg border border-destructive/30 px-3 py-2 text-xs font-bold"><RefreshCw size={14}/>إعادة المحاولة</button></div> : <>{rows.length ? <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-secondary/70 p-3"><p className="text-[11px] text-muted-foreground">عدد السجلات</p><p className="mt-1 text-xl font-extrabold">{rows.length}</p></div><div className="rounded-xl bg-primary/10 p-3"><p className="text-[11px] text-muted-foreground">إجمالي القيم المسجلة</p><p className="mt-1 text-xl font-extrabold text-primary">{totalAmount.toLocaleString("en-US")}</p></div><div className="rounded-xl bg-amber-500/10 p-3"><p className="text-[11px] text-muted-foreground">منفذة · قيد المراجعة</p><p className="mt-1 text-xl font-extrabold text-amber-700 dark:text-amber-300">{statusCounts.executed ?? 0} · {statusCounts.review ?? 0}</p></div></div> : null}<p className="mt-4 text-sm text-muted-foreground">{report.isLoading ? "جارٍ تطبيق التصفية…" : rows.length ? `${rows.length} سجل جاهز للتصدير وفق التصفية الحالية.` : "لا توجد سجلات مطابقة للتصفية الحالية."}</p></>}
  </section>;
}
